[package]
name = "brdns"
version = "0.1.0"
edition = "2024"



[lib]
path = "lib/mod.rs"

[[bin]]
name = "g"
path = "bin/g.rs"

[dependencies]
async-trait = "0.1.89"
base64 = "0.22.1"
clap = { version = "4.6.2", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["query"]}
rustls = "0.23.42"
tokio = { version = "1.53.0", features = ["full"] }
tokio-rustls = "0.26.4"
webpki-roots = "1.0.9"
# For DNS over TLS
#rustls = "0.23"
#webpki-roots = "0.26"

# For DNS over HTTPS
#reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
#base64 = "0.22"

# For async (DoT/DoH benefit from this)
#tokio = { version = "1", features = ["full"] }
